apiVersion: v1
kind: Secret
metadata:
  name: dl-secrets
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  secrets.yaml: |
    secrets:
      webdav_url: {{ .Values.secrets.webdav_url | quote }}
      webdav_username: {{ .Values.secrets.webdav_username | quote }}
      webdav_password: {{ .Values.secrets.webdav_password | quote }}
      master_key: {{ .Values.secrets.master_key | quote }}
      jwt_secret: {{ .Values.secrets.jwt_secret | quote }}
